# Generated by Django 5.0.7 on 2025-12-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("image", models.ImageField(upload_to="projects/")),
                ("description", models.TextField()),
                ("client", models.CharField(blank=True, max_length=200)),
                ("url", models.URLField(blank=True)),
                ("technologies", models.CharField(max_length=500)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="FontAwesome or Heroicon class",
                        max_length=100,
                    ),
                ),
                ("short_description", models.TextField(help_text="For list view")),
                ("content", models.TextField(help_text="Detailed content")),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of features"
                    ),
                ),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated technologies",
                        max_length=500,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("rating", models.IntegerField(default=5)),
            ],
        ),
    ]
