# Generated by Django 5.0.7 on 2025-12-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_newsletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projects_completed", models.PositiveIntegerField(default=0)),
                ("happy_clients", models.PositiveIntegerField(default=0)),
                ("team_members", models.PositiveIntegerField(default=0)),
                ("experience_years", models.PositiveIntegerField(default=3)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=150)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="employees/photos/"
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="TechOhr", max_length=200)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="settings/logo/"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="settings/favicon/"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("email_primary", models.EmailField(blank=True, max_length=254)),
                ("email_support", models.EmailField(blank=True, max_length=254)),
                ("phone_primary", models.CharField(blank=True, max_length=50)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True, help_text="Paste the Google Maps embed URL"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
