# Generated by Django 5.0.7 on 2025-12-18 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_companystats_employee_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="logo_dark",
            field=models.ImageField(blank=True, null=True, upload_to="settings/logo/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_light",
            field=models.ImageField(blank=True, null=True, upload_to="settings/logo/"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.project",
            ),
        ),
    ]
