from django.test import TestCase, Client
from django.urls import reverse
from .models import Project

class HomeViewTests(TestCase):
    def setUp(self):
        self.client = Client()

    def test_home_page_status_code(self):
        response = self.client.get(reverse('home'))
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, 'core/home.html')

class ProjectTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.project = Project.objects.create(
            title='Test Project',
            description='Test Description',
            technologies='Python, Django'
        )
        # Slug should be auto-generated by save()

    def test_project_slug_generation(self):
        self.assertEqual(self.project.slug, 'test-project')

    def test_project_detail_view(self):
        url = reverse('project_detail', args=[self.project.slug])
        response = self.client.get(url)
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, 'core/project_detail.html')
        self.assertContains(response, 'Test Project')
