# Generated by Django 5.0.7 on 2025-12-10 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="content",
        ),
        migrations.AddField(
            model_name="course",
            name="has_certificate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="assignment_instruction",
            field=models.TextField(
                blank=True, help_text="Instructions for the assignment"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="document_file",
            field=models.FileField(
                blank=True,
                help_text="PDF, PPT, or other files",
                null=True,
                upload_to="courses/documents/",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("article", "Article/Text"),
                    ("quiz", "Quiz"),
                    ("assignment", "Assignment"),
                    ("document", "Document (PDF/PPT)"),
                ],
                default="video",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="text_content",
            field=models.TextField(
                blank=True, help_text="For Articles or Video Descriptions"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload video file directly",
                null=True,
                upload_to="courses/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(upload_to="courses/thumbnails/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_free",
            field=models.BooleanField(
                default=False, help_text="Preview available without enrollment"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="YouTube/Vimeo URL (if not uploading)"
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="courses.enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.lesson"
                    ),
                ),
            ],
            options={
                "unique_together": {("enrollment", "lesson")},
            },
        ),
    ]
