# Generated by Django 5.0.7 on 2025-12-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_enrollment_progress_remove_lesson_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a background image for the certificate.",
                        null=True,
                        upload_to="certificates/backgrounds/",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a logo to appear on the certificate.",
                        null=True,
                        upload_to="certificates/logos/",
                    ),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a signature image.",
                        null=True,
                        upload_to="certificates/signatures/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#1a202c",
                        help_text="Primary text color (Hex code, e.g., #000000)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#4a5568",
                        help_text="Secondary text color (Hex code, e.g., #555555)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#3182ce",
                        help_text="Accent color for borders/lines (Hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        choices=[
                            ("Helvetica", "Helvetica"),
                            ("Times", "Times"),
                            ("Courier", "Courier"),
                        ],
                        default="Helvetica",
                        help_text="Font family for the certificate.",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Certificate Design",
                "verbose_name_plural": "Certificate Designs",
            },
        ),
    ]
