# Generated by Django 5.0.7 on 2025-12-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_certificatesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatesettings",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("Helvetica", "Helvetica"),
                    ("Times", "Times"),
                    ("Courier", "Courier"),
                    ("GreatVibes", "Great Vibes (Script)"),
                    ("Lato", "Lato (Modern Sans)"),
                ],
                default="Helvetica",
                help_text="Font family for the certificate.",
                max_length=50,
            ),
        ),
    ]
