# Generated by Django 5.0.7 on 2025-12-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="discounted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted Price (if set, this will be the selling price)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="Normal Price", max_digits=10
            ),
        ),
    ]
