# Generated by Django 5.0.7 on 2026-02-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_discounted_price_alter_course_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paystack_public_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "paystack_secret_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_public_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_secret_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Payment Settings",
                "verbose_name_plural": "Payment Settings",
            },
        ),
    ]
