# Generated by Django 4.2.13 on 2026-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_paymentsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="digital_file",
            field=models.FileField(
                blank=True,
                help_text="The file students can download after purchase if this is a digital product.",
                null=True,
                upload_to="courses/products/",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_digital_product",
            field=models.BooleanField(
                default=False,
                help_text="Check if this is a stand-alone digital product (e.g. eBook) instead of a course.",
            ),
        ),
    ]
